import type { Writable } from 'svelte/store'
import { writable } from 'svelte/store';
export const quotes:Writable<[]> = writable([])
const inspirationalPhrases: string[] = [
  "You're unstoppable.",
  "Shine bright like a star.",
  "Embrace the journey.",
  "Your potential is limitless.",
  "Keep going, you're making progress.",
  "Believe in your dreams.",
  "You've got this!",
  "Today is your day.",
  "Radiate positivity.",
  "Strive for greatness.",
  "Every step counts.",
  "Your effort is paying off.",
  "Make today amazing.",
  "Stay focused, stay strong.",
  "You're a force of nature.",
  "Dream big, work hard.",
  "Rise above the challenges.",
  "Your strength is incredible.",
  "Keep pushing forward.",
  "Inspire others with your passion.",
  "Believe in the power within you.",
  "Conquer your fears.",
  "Transform challenges into opportunities.",
  "Your resilience is admirable.",
  "Keep the faith, miracles happen.",
  "Embrace the possibilities.",
  "Radiate positive vibes.",
  "Your journey is unique and beautiful.",
  "You're on the path to success.",
  "Embrace the magic within you.",
  "Your determination is inspiring.",
  "Seize the day with confidence.",
  "Your courage knows no bounds.",
  "Every effort brings you closer.",
  "Your potential is extraordinary.",
  "Shine like the star you are.",
  "Keep dreaming, keep achieving.",
  "Today is a gift, cherish it.",
  "Trust the process.",
  "Your perseverance is unmatched.",
  "Believe in the beauty of your dreams.",
  "Strive for progress, not perfection.",
  "You're stronger than you think.",
  "Embrace challenges as opportunities.",
  "Your journey is unfolding perfectly.",
  "Keep your head high, keep your heart higher.",
  "The world needs your unique light.",
  "You're making a positive impact.",
  "Your passion fuels your success.",
  "Keep moving forward with purpose.",
  "Your kindness is your strength.",
  "Embrace the joy of the present moment.",
  "Rise above the storm, find the sunshine.",
  "Your determination is your superpower.",
  "Inspire others by being yourself.",
  "Celebrate your victories, big or small.",
  "You are enough, just as you are.",
  "Your resilience is your greatest strength.",
  "Embrace the beauty of each day.",
  "Believe in your ability to overcome.",
  "Your journey is sculpting a masterpiece.",
  "Keep chasing your dreams fearlessly.",
  "Radiate positivity and kindness.",
  "Your potential is boundless.",
  "Embrace the power of positivity.",
  "You're on the brink of something amazing.",
  "Keep your head high, keep your spirits higher.",
  "Trust in your inner strength.",
  "Shine on, you magnificent soul.",
  "Your journey is a testament to your strength.",
  "Embrace the adventure of self-discovery.",
  "You're a beacon of inspiration.",
  "Your possibilities are endless.",
  "Keep pushing boundaries.",
  "Believe in the magic of new beginnings.",
  "Your resilience is rewriting your story.",
  "Embrace the challenges, they shape you.",
  "You're making a positive difference.",
  "Radiate love and positivity.",
  "Your journey is an inspiration to others.",
  "Keep blooming, beautiful soul.",
  "Believe in the power of your dreams.",
  "Embrace the abundance of the universe.",
  "You're a catalyst for positive change.",
  "Keep evolving, keep growing.",
  "Your strength is your foundation.",
  "Shine bright, live boldly.",
  "Trust in the process of becoming.",
  "You're creating your own sunshine.",
  "Embrace the power within you.",
  "Your authenticity is your superpower.",
  "Keep believing in the extraordinary.",
  "Rise above, radiate love.",
  "Your journey is sculpting your legacy.",
  "Embrace the beauty of resilience.",
  "You're a source of inspiration to many.",
  "Keep soaring, sky's the limit.",
  "Believe in the beauty of your dreams.",
  "Your potential knows no boundaries.",
  "Embrace the journey, embrace the joy."
];
